[phases.setup]
nixPkgs = ['...', 'cairo', 'pango', 'libjpeg', 'giflib', 'librsvg', 'pixman']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'